# NATS Server Configuration

server_name: nats-score-server
port: 4222
http_port: 8222

jetstream {
    store_dir: /data/jetstream
    max_memory_store: 268435456   # 256MB
    max_file_store: 1073741824    # 1GB
}

websocket {
    port: 8080
    no_tls: true
}

debug: false
trace: false
logtime: true

# =============================================================================
# Authorization
# =============================================================================
authorization {
    users = [
        # Admin - full access
        {
            user: admin,
            password: "adminpass",
            permissions: {
                publish: [">"]
                subscribe: [">"]
               allow_responses: true
            }
        }

        # Teams - scoped to their own keys within the shared KV bucket
        # Each team can only read/write to keys prefixed with their team name
        {
            user: team1,
            password: "team1-secret",
            permissions: {
                publish: [
                    "results.1.>",
                    # "settings.1.>",
                    # "$KV.settings.1.>",
                    "$JS.API.INFO",
                    "$JS.API.STREAM.INFO.KV_settings",
                    "$JS.API.STREAM.MSG.GET.KV_settings",
                    "$JS.API.DIRECT.GET.KV_settings.>",
                    "$JS.API.CONSUMER.>"
                ]
                subscribe: [
                    "settings.1.settings",
                    "$KV.settings.1.settings",
                    "_INBOX.>",
                    "events.score.>"  # Ephemeral events (non-JetStream)
                ]
                allow_responses: true
            }
        }
    ]
}
