version: 2

project_name: score

before:
  hooks:
    - sh -c "cd frontend && npm ci --ignore-scripts && npm run build"
    - sh -c "rm -rf server/internal/static/dist && cp -r frontend/dist server/internal/static/dist"

builds:
  - main: ./cmd/cli/main.go
    dir: ./server/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files: []

dockers_v2:
  - id: score
    images:
      - "ghcr.io/andrew-aiken/score"
    tags:
      - "v{{ .Version }}"
      - "latest"
    extra_files:
      - frontend/
      - server/
    labels:
      "project": "{{.ProjectName}}"
    annotations:
      "org.opencontainers.image.description": "Distributed scoring engine"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.base.name": "{{.BaseImage}}"
      "org.opencontainers.image.base.digest": "{{.BaseImageDigest}}"
    platforms:
      - linux/amd64
    sbom: false
    flags:
      - "--provenance=false"

changelog:
  sort: asc
  filters:
    exclude:
      - "^example:"
      - "^test:"
