services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8080:8080"
    volumes:
      - ./nsc/nats.conf:/etc/nats/server.conf:ro
      - ./nsc/score/score.jwt:/etc/nats/operator.jwt:ro
    command: ["-c", "/etc/nats/server.conf"]

  setup:
    depends_on:
      - nats
    build:
      context: ./
      target: server
    restart: no
    volumes:
      - ./scripts/startup.sh:/opt/startup.sh:ro
      - ./nsc/config.json:/opt/config.json:ro
      - ./nsc/creds/score/score/server.creds:/server.creds:ro
      - ./example:/checks:ro
      - shared:/shared
    entrypoint:
      - bash
      - /opt/startup.sh

  server:
    container_name: server
    depends_on:
      setup:
        condition: service_completed_successfully
    build:
      context: ./
    working_dir: /
    volumes:
      - ./nsc/config.json:/config.json:ro
      - ./nsc/creds/score/score/server.creds:/server.creds:ro
    ports:
      - "3000:3000"

  agent:
    container_name: agent
    depends_on:
      setup:
        condition: service_completed_successfully
    build:
      context: ./
    volumes:
      - ./nsc/config.json:/opt/config.json:ro
      - shared:/shared:ro
    command:
      - agent
      - --team
      - "0"
      - --nats-address
      - nats://localhost:4222
      - --nats-creds
      - /shared/agent.creds
    network_mode: host

volumes:
  shared:
