services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8080:8080"
    volumes:
      - ./nats/nats-server.conf:/etc/nats/nats-server.conf:ro
      - ./nats/nsc/score/score.jwt:/etc/nats/operator.jwt:ro
    command: ["-c", "/etc/nats/nats-server.conf"]

  setup:
    depends_on:
      - nats
    build:
      context: ./
      target: server
    restart: no
    volumes:
      - ./config.json:/opt/config.json:ro
      - ./startup.sh:/opt/startup.sh
      - /Users/aaiken/ccdc/nats-score/nats/nsc/creds/score/score/server.creds:/server.creds:ro
      - ./checks:/checks:ro
    entrypoint:
      - bash
      - /opt/startup.sh

  server:
    container_name: server
    depends_on:
      - setup
    build:
      context: ./
    volumes:
      - ./config.json:/opt/config.json:ro
      - /Users/aaiken/ccdc/nats-score/nats/nsc/creds/score/score/server.creds:/server.creds:ro
    command:
      - server
      - --config
      - /opt/config.json
      - start
    ports:
      - "3000:3000"
